# Spark master
spark.master                           spark://spark-master:7077 

# Enable event logging
spark.eventLog.enabled                 true
spark.eventLog.dir                     /opt/spark/events   
spark.history.fs.logDirectory          /opt/spark/events